# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jVUUcVvlG4qQk5YxywcLlqfTHPKkWXxt
"""

!pip install streamlit -q
!pip install pyngrok  # Or use localtunnel

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import joblib
# import os
# 
# st.set_page_config(page_title="HKJC Prediction", layout="centered")
# st.title("🏇 HKJC Smart Predictor")
# 
# model_path = 'random_forest_model.pkl'
# 
# if os.path.exists(model_path):
#     model = joblib.load(model_path)
# 
#     st.subheader("Race Information")
#     distance = st.selectbox("Race Distance (m)", [1000, 1200, 1400, 1600, 1650, 1800, 2000, 2200, 2400])
# 
#     st.subheader("Horse Statistics")
#     col1, col2 = st.columns(2)
# 
#     with col1:
#         top3_count = st.slider("How many Top-3 finishes in last 3 races?", 0, 3, 1)
#         speed_rating = st.number_input("Historical Speed Rating", value=75.0)
#         actual_weight = st.number_input("Horse's Weight (lbs)", value=120.0)
# 
#     with col2:
#         days_since = st.number_input("Days Since Last Run", value=14)
#         class_move = st.selectbox("Class Change", options=[-1, 0, 1], format_func=lambda x: "Down" if x==-1 else ("Up" if x==1 else "Same"))
#         barrier = st.slider("Barrier (Draw)", 1, 14, 7)
# 
#     # Calculate engineered features behind the scenes
#     avg_race_weight = 120.0 # You can adjust this or make it an input
# 
#     # Feature 1: P3R_Top3_Pct_x_Dist
#     top3_pct = top3_count / 3.0
#     calc_p3r_dist = top3_pct * distance
# 
#     # Feature 2: Rel_Weight_x_Dist
#     calc_rel_weight_dist = (actual_weight / avg_race_weight) * distance
# 
#     if st.button("Predict Top 3 Finish"):
#         # Match the EXACT order of your 'selected_features' list
#         data = {
#             'P3R_Top3_Pct_x_Dist': calc_p3r_dist,
#             'Days_Since_Last_Run': days_since,
#             'Rel_Weight_x_Dist': calc_rel_weight_dist,
#             'Barrier_Rank': barrier,
#             'Class_Change': class_move,
#             'Hist_Speed_Rating': speed_rating
#         }
# 
#         # Define order specifically to avoid ValueError
#         feature_order = ['P3R_Top3_Pct_x_Dist', 'Days_Since_Last_Run', 'Rel_Weight_x_Dist',
#                          'Barrier_Rank', 'Class_Change', 'Hist_Speed_Rating']
# 
#         input_df = pd.DataFrame([data])[feature_order]
# 
#         prediction = model.predict(input_df)
#         prob = model.predict_proba(input_df)[0][1]
# 
#         if prediction[0] == 1:
#             st.success(f"High Probability of Top 3! ({prob:.2%})")
#         else:
#             st.warning(f"Low Probability of Top 3. ({prob:.2%})")
# else:
#     st.error("Model file not found in sidebar!")

